#+STARTUP: hidestars

* [[http://rosalind.info/problems/dna/][A Rapid Introduction to Molecular Biology]]
  The cell, the building block of life, contains a nucleus
  filled with chromatin. The Deoxyribose Nucleic Acids are
  found in chromatin and are strands of similarly structured
  molecules; in other words, they are polymers made of
  monomers called nucleotides.

  During mitosis, chromatin condenses into strings called
  chromosomes, made of super-coils of nucleosomes and
  proteins. Nucleosomes are made of the DNA in the
  chromatin, coiled around proteins called histones. 

  .o0(seems to me that they coil into compacted balls of an
  incredible amount of data before splitting, leaving the
  original and new cell with the same copy of the data. But
  then how does a chromosome know to build - itself - in
  such a way that it can be split equally? Or maybe that is
  not what happens and both sides of a the symmetrical
  chromosome contain different info? I'm pretty sure i'll
  learn about that in the later chapters, even if i already
  did and forgotten.)

  A nucleotide consists of 3 parts:
  - sugar, a monosaccharide called deoxyribose
  - phosphate (some kind of salt)
  - nucleobase compound
    - Adenine
    - Cytosine
    - Guanine
    - Thymine
    - Uracil (to be discussed later in regards to RNA)

  To form a chain of these nucleotides monomers into a
  polymer, the sugar of one attaches to the phosphate of
  another to for the backbone of a strand, and the bases
  attract each other (with this rule: A ⇔ T, C ⇔ G) to form
  the double helix DNA from two spiraling strands.

  All living organisms on Earth have DNA, including
  bacteria, but not all viruses.

  .o0(viruses are considered non-living, but bacteria are
  alive, so antibiotics can recognize them and kill them. is
  that how it works? how does a virus infection "run its
  course"? See [[*%5B%5Bhttps://en.wikipedia.org/wiki/Virus%5D%5BVirus%5D%5D][#Virus]].)
* The Second Nucleic Acid
  Along with the DNA molecule, the Ribose Nucleic Acid also
  exists in the chromatin. RNA is very similar in structure
  to DNA, except:
  - the sugar is called ribose instead of deoxyribose
  - the Uracil nucleobase replaces DNA's Thymine
  - it's a single strand, 
  - it can go outside of the nucleus

  RNA is created from DNA via an enzyme called RNA
  Polymerase during RNA Transcription. The 3'-5' strand of a
  DNA is the template strand, the other is the coding
  strand. At the end of the transcription, a pre-messenger
  RNA will be the exact copy of the coding strand, except
  the pre-mRNA will have the Uracil nucleobase instead of
  Thymine.

  .o0(when is it just an RNA?)
* [[http://rosalind.info/problems/revc/][The Secondary and Tertiary Structures of DNA]]
  This chapter re-iterates the double-helix shape of DNA
  strands, which was proposed by James Watson and Francis
  Crick in 1953.

  The complementary bases (A ↔ T and C ↔ G) are also called
  "base-pairs", or "bp" for short.
* [[http://rosalind.info/problems/fib/][Wascally Wabbits]]
  This chapter covers the Fibonacci series, a man also known
  as Leonardo de Pisa, and how he solved a
  somewhat-fictional problem of immortal rabbits reproducing
  indefinitely, and that a pair of rabbits will attain a
  count of 144 in a year.

  .o0(it closely ties to cell reproduction, perhaps.)

  Recurrence Relation is adding the next value of a sequence
  based on the previous values.

  Dynamic Programming is storing calculation for values into
  a lookup table to be performed when needed, i.e. when
  calculating a future value in a sequence via Recurrence
  Relation; recursively calculate previous values.

  .o0(in Lisp, that is similar to "memoization", if not
  exactly that.)
* Glossary
  - chromatin :: dense collection of nucleic acids (40%) and
                 proteins found in the nucleus that's
                 attracted to dye, hence the name.
  - genome :: sum total of DNA in an organism
  - eukaryotic :: of the multicellular domain of life, yet
                  including some unicellular ones, but seems
                  like the cells contain a nucleus, a.k.a.
                  the brain.
  - mitosis :: the change involving a eukaryotic cell
               division.
  - phosphate :: 1 of 3 parts that form the nucleic acid, or
                 nucleotide; this one a negatively-charged
                 ion, PO₄
* Sidebar
** [[https://en.wikipedia.org/wiki/Virus][Virus]]
   - only replicates inside living cells
   - consists of 2 or 3 things:
     1. a genetic material: DNA, RNA, or molecules with
        genetic information
     2. a protein coat, called capsid, around the genetic
        material
     3. envelope of lipids over the coat when outside the
        cell

   Viruses could be considered life because of the genetic
   material, reproduction, and evolution, but they don't
   have a cell structure (like a nucleus?) to actually be
   living.

   The immune system will kill the virus infection. If the
   body can not fight it on its own, vaccination is given to
   teach it how to; the host's immune system recognizes the
   threat in the vaccine, a weakened or dead virus, kills it
   and learns how to do so later on.

   .o0(if the body was not yet vaccinated, then i think
   blood (like white cells) from a strong immune system is
   transfused into the virus-infected host to help fight and
   teach the host.)
* Lisp
** Getting started
   #+BEGIN_EXAMPLE
     M-x slime<ret>
     CL-USER> (ql:quickload "dna")
     CL-USER> (in-package "dna")
     CL-USER> *sample*
   #+END_EXAMPLE
